### ISSUE TITLE
Unexpected value 'NgxEditorModule' imported by the module 'AppModule'. Please add a @NgModule annotation

### ISSUE THREAD

**Issue by alex88** [Sibiraj-S/ngx-editor#19]
After adding this into my module file

```
import { NgxEditorModule } from 'ngx-editor';

@NgModule({
  imports: [
    BrowserModule,
    ....
    NgxEditorModule
 ]})
```
I get the above error:

```
Uncaught Error: Unexpected value 'NgxEditorModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (webpack:///./node_modules/@angular/compiler/@angular/compiler.es5.js?:1918:34)
    at eval (webpack:///./node_modules/@angular/compiler/@angular/compiler.es5.js?:15610:44)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (webpack:///./node_modules/@angular/compiler/@angular/compiler.es5.js?:15593:49)
    at JitCompiler._loadModules (webpack:///./node_modules/@angular/compiler/@angular/compiler.es5.js?:27023:70)
    at JitCompiler._compileModuleAndComponents (webpack:///./node_modules/@angular/compiler/@angular/compiler.es5.js?:26996:36)
    at JitCompiler.compileModuleAsync (webpack:///./node_modules/@angular/compiler/@angular/compiler.es5.js?:26925:37)
    at PlatformRef_._bootstrapModuleWithZone (webpack:///./node_modules/@angular/core/@angular/core.es5.js?:4740:25)
    at PlatformRef_.bootstrapModule (webpack:///./node_modules/@angular/core/@angular/core.es5.js?:4726:21)
    at eval (webpack:///./src/main.ts?:11:109)
    at Object.576 (http://localhost:3000/assets/js/main.js:257:1)
    at __webpack_require__ (http://localhost:3000/assets/js/vendor.js:55:30)
    at eval (webpack:///multi_(webpack)-dev-server/client?:2:1)
    at Object.575 (http://localhost:3000/assets/js/main.js:249:1)
    at __webpack_require__ (http://localhost:3000/assets/js/vendor.js:55:30)
    at webpackJsonpCallback (http://localhost:3000/assets/js/vendor.js:26:23)
    at http://localhost:3000/assets/js/main.js:1:1
```

is there anything I'm missing?

**Comment by alex88** [comment]
Nvm found it, I've solved it with https://github.com/angular/angular/issues/14898#issuecomment-290359551
