### ISSUE TITLE
[Bug]: looks like multiple versions of prosemirror-model were loaded

### ISSUE THREAD

**Issue by jegjessing** [sibiraj-s/ngx-editor#431]
### What happened?

After updating to these versions I'm getting the above error and I cannot use the editor since it cuts out the line

### Version

v13.0.0

### Angular Version

v13.3.10

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
core.mjs:6494 ERROR RangeError: Can not convert <"Js"> to a Fragment (looks like multiple versions of prosemirror-model were loaded)
    at Fragment.from (index.js:354:1)
    at NodeType.create (index.js:2136:1)
    at NodeContext.finish (index.js:2685:1)
    at ParseContext.finish (index.js:2992:1)
    at DOMParser.parse (index.js:2513:1)
    at parseBetween (index.js:4437:1)
    at readDOMChange (index.js:4498:1)
    at DOMObserver.handleDOMChange (index.js:4832:1)
    at DOMObserver.flush (index.js:4336:1)
    at DOMObserver.observer (index.js:4215:1)
```

**Comment by sibiraj-s** [comment]
Sometimes this happens. have you manually installed prosemirror-model? If yes try updating that to the version required by the editor. If not, or still it doesn't work try deleting node_modules and package-lock.json and reinstall.

**Comment by jegjessing** [comment]
Thanks but no luck and i did not Install it manually.


I upgraded to 14 and angular and editor now all works :-)

**Comment by sibiraj-s** [comment]
Nice 👍 . Closing this issue as it is fixed.
