### ISSUE TITLE
Build error when compiling as part of a package with ng-packagr

### ISSUE THREAD

**Issue by stephanos199** [Sibiraj-S/ngx-editor#50]
```
BUILD ERROR
'fromTextArea' is not exported by node_modules\codemirror\lib\codemirror.js
Error: 'fromTextArea' is not exported by node_modules\codemirror\lib\codemirror.js
    at error (\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error (\node_modules\rollup\dist\rollup.js:16526:3)
    at Module.trace (\node_modules\rollup\dist\rollup.js:16623:10)
    at ModuleScope.findVariable (\node_modules\rollup\dist\rollup.js:13965:22)
    at FunctionScope.findVariable (\node_modules\rollup\dist\rollup.js:11543:33)
    at Scope.findVariable (\node_modules\rollup\dist\rollup.js:11543:33)
    at FunctionScope.findVariable (\node_modules\rollup\dist\rollup.js:11543:33)
    at Scope.findVariable (\node_modules\rollup\dist\rollup.js:11543:33)
    at BlockScope.findVariable (\node_modules\rollup\dist\rollup.js:11543:33)
    at Node._bindVariableIfMissing (\node_modules\rollup\dist\rollup.js:12626:31)
```

To reproduce create a project, use the component and then try to compile using ng packagr

**Comment by Sibiraj-S** [comment]
I have been using it in my project. I have no errors. Have you installed `codemirror` which is a `peerDependency`. Which version are you using.

**Comment by stephanos199** [comment]
I'm using version 3.3.0-rc.3 of the editor and have codemirror version 5.34.0 as a peer dependency.

**Comment by Sibiraj-S** [comment]
That's odd. I was using that version in out product. Which is in production actually.

You can see a working example here: https://ngx-editor.stackblitz.io/
Code for the example: https://stackblitz.com/edit/ngx-editor

Post More Information such as
1. Angular version
2. Operation System
3. Nodejs version

If nothing helps.

**Comment by Sibiraj-S** [comment]
@stephanos199 . Did that help?

**Comment by stephanos199** [comment]
I only had to add 

```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts",
    "externals": {
      "codemirror": "codemirror"
    }
  }
}
```

I was missing the `"externals"` declaration

**Comment by Sibiraj-S** [comment]
So Is it working now?

**Comment by stephanos199** [comment]
Yes

**Comment by Sibiraj-S** [comment]
Closing as PROBLEM RESOLVED
