### ISSUE TITLE
[Bug]: Unexpected token ':'

### ISSUE THREAD

**Issue by jowin202** [sibiraj-s/ngx-editor#540]
### What happened?

Hi,
I'm following this tutorial (https://sibiraj-s.github.io/ngx-editor/introduction/) and I do exactly what it is said

```
ng new editortest2 (SCSS and SSR: yes)
cd editortest2
npm install ngx-editor
```

Then I put
`import { NgxEditorModule } from 'ngx-editor';`
into my component

and I add `NgxEditorModule` to my imports ... now the error is here.

### Version

newest: "npm install ngx-editor" on ubuntu 24.04

### Angular Version

newest under ubuntu 24.04

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
Unexpected token ':'

    at new AsyncFunction (<anonymous>)
    at instantiateModule (file:///home/johannes/angular/editortest2/node_modules/vite/dist/node/chunks/dep

20:12:36 [vite] Error when evaluating SSR module /main.server.mjs:
|- SyntaxError: Unexpected token ':'
    at new AsyncFunction (<anonymous>)
    at instantiateModule (file:///home/johannes/angular/editortest2/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:54894:28)

20:12:36 [vite] Internal server error: Unexpected token ':'
      at new AsyncFunction (<anonymous>)
      at instantiateModule (file:///home/johannes/angular/editortest2/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:54894:28)
```

### Willing to submit a PR?

None (maybe later if I'm more advanced in angular/ts)

**Comment by sibiraj-s** [comment]
May be same as https://github.com/sibiraj-s/ngx-editor/issues/520

**Comment by nacaru-w** [comment]
Getting the same error using Angular 17.3, did you find a solution? @jowin202

**Comment by DanielePetraliaDev** [comment]
I had the same problem and solved adding 
`await import('ngx-editor');`
at the end of ngOnInit after checking I'm in browser.
I don't know why it works but for me it does.

**Comment by sibiraj-s** [comment]
Yeah the reason it could be working is when you do `await import` it might excluded in the SSR compilation process. 

The reason this happens is because, the underlying library prosemirror doesn't support SSR, reason here https://github.com/sibiraj-s/ngx-editor/issues/520#issuecomment-2010306994

**Comment by sibiraj-s** [comment]
Closing this, since the editor needs to be rendered on client due to prosemirror requirements. Nothing to fix here.

See https://github.com/sibiraj-s/ngx-editor/blob/fe5591354cf0ac342de7e692a89d4a0025dc6cf4/projects/demo/src/app/app.router.server.ts for how to skip a page on ssr if required.
